-- AlterTable
ALTER TABLE "DeletedFile" ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "DeletedFileVersion" ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "File" ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "FileVersion" ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 0;
