DROP DATABASE IF EXISTS `data`;
CREATE DATABASE `data`;
USE `data`;
SET NAMES utf8;
SET character_set_client = utf8mb4;

CREATE TABLE `folders`(
    `DIRID` INTEGER AUTO_INCREMENT PRIMARY KEY,
    `DIRECTORY` VARCHAR(255) NOT NULL UNIQUE,
    `DEVICE` VARCHAR(70) NOT NULL
);

CREATE TABLE `files`(
    `ID` INTEGER AUTO_INCREMENT PRIMARY KEY,
    `USERNAME` VARCHAR(70) NOT NULL,
    `DIRID` INTEGER NOT NULL,
    `FILENAME` VARCHAR(255) NOT NULL,
    `FILE_LMD` DATETIME NOT NULL,
    `CHECKSUM` CHAR(64) NOT NULL,
    `VERSIONS` INTEGER NOT NULL,
    `SNAPSHOT` VARCHAR(255) NOT NULL,
    FOREIGN KEY (`USERNAME`) REFERENCES customers.users(`username`),
    FOREIGN KEY (`DIRID`) REFERENCES data.folders(`DIRID`)
);