-- AlterTable
ALTER TABLE "User" ADD COLUMN     "OTPGenTime" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "OTPValidity" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "hotpCounter" BIGINT NOT NULL DEFAULT 0;
