-- AlterTable
ALTER TABLE "User" ADD COLUMN     "SSO_EndPoint" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "cert" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "isSSO" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "issuer_URL" TEXT NOT NULL DEFAULT '';
